FROM python:3

WORKDIR /app

ADD ./src /app

RUN pip install -r requirements.txt

RUN chmod +x haproxy

CMD ./haproxy -f haproxy.cfg -D && gunicorn --keep-alive 10 -k gevent --bind 127.0.0.1:3000 -w 20 backend:app --access-logfile '-'

