version: '3.8'

services:
  web:
    image: apache_gunicorn
    container_name: apache_forwarded_ip
    build: .
    restart: always
    ports:
      - "8087:80"
    volumes:
      - ./src:/app:ro
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro