FROM httpd:2.4.38

WORKDIR /app

RUN apt-get update

RUN apt-get install python3 python3-pip -y

RUN pip3 install flask gunicorn

EXPOSE 80

CMD /usr/local/apache2/bin/httpd -k start && cd /app/ &&  gunicorn --bind=127.0.0.1:3000 wsgi:app --access-logfile '-'
