version: '3.8'

services:
  frontend:
    image: nginx:1.21.1
    container_name: nginx_tomcat_inconsistency_frontend
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    image: tomcat
    container_name: nginx_tomcat_inconsistency_backend
    build:
      context: ./backend
    restart: always
    volumes:
      - ./backend/src:/usr/local/tomcat/webapps/ROOT:ro

