version: '3.8'

services:
  frontend:
    image: httpd:2.4.48
    container_name: apache-gunicorn-frontend
    restart: always
    ports:
      - "9094:80"
    volumes:
      - ./frontend/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
  
  backend:
    image: ubuntu_gunicorn
    container_name: apache-gunicorn-backend
    build: ./backend
    restart: always
    volumes:
      - ./backend/src:/app:ro

