version: '3.8'

services:
  frontend:
    image: nginx:1.21.1
    container_name: nginx-gunicorn-frontend
    restart: always
    ports:
      - "9093:80"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
  
  backend:
    image: ubuntu_gunicorn
    container_name: nginx-gunicorn-backend
    build: ./backend
    restart: always
    volumes:
      - ./backend/src:/app:ro

