version: '3.8'

services:
  web:
    image: httpd:2.4.48
    container_name: httpdtest
    restart: always
    ports:
      - "9091:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs:ro
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
