FROM nginx:1.21.1

RUN apt-get update

RUN apt-get install php7.3-fpm -y

COPY ./src /usr/share/nginx/html

COPY ./conf/www.conf /etc/php/7.3/fpm/pool.d/www.conf

COPY ./conf/default.conf /etc/nginx/conf.d/default.conf

RUN mkdir /var/run/php

CMD /usr/sbin/php-fpm7.3 && nginx -g "daemon off;"

