version: '3.8'

services:
  frontend:
    image: nginx:1.21.1
    container_name: nginx-apache-frontend
    restart: always
    ports:
      - "8083:80"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
  
  backend:
    image: httpd:2.4.48
    container_name: nginx-apache-backend
    restart: always
    volumes:
      - ./backend/src:/usr/local/apache2/htdocs:ro

